# pylint: disable=unused-argument
from typing import Any, ContextManager


def window(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def tab_bar(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def tab(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def child_window(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def group(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def table(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def menu_bar(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def menu(*args: Any, **kwargs: Any) -> ContextManager[int]: ...
def collapsing_header(*args: Any, **kwargs: Any) -> ContextManager[int]: ...


def __getattr__(name: str) -> Any: ...
